/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author R16
 */
public class guimenu extends javax.swing.JFrame {

    /**
     * Creates new form guimenu
     */
    Graphics g;

    public guimenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpane = new javax.swing.JOptionPane();
        panelMenu = new javax.swing.JPanel();
        btnOlahData = new javax.swing.JLabel();
        btnOlahJadwal = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        panelmenuawal = new javax.swing.JPanel();
        btnDosen = new javax.swing.JLabel();
        btnMk = new javax.swing.JLabel();
        btnKls = new javax.swing.JLabel();
        btnRuang = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        panelOlahjadwal = new javax.swing.JPanel();
        btnInputjadwal = new javax.swing.JLabel();
        btnViewJadwalSemua = new javax.swing.JLabel();
        btnviewJadwal1bln = new javax.swing.JLabel();
        btnviewHari = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelInputJadwal = new javax.swing.JPanel();
        panelview1hari = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableViewharijadwal = new javax.swing.JTable();
        panelViewJadwalbulan = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableviewjadwalbulan = new javax.swing.JTable();
        panelviewJadwalAll = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableViewalljadwal = new javax.swing.JTable();
        panelOlahDosen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fieldkdosen = new javax.swing.JTextField();
        fieldnamadosen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnsavedosen = new javax.swing.JLabel();
        btncanceldosen = new javax.swing.JLabel();
        btnhpsdosen = new javax.swing.JLabel();
        btnviewdosen = new javax.swing.JLabel();
        panelViewDosen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewDosen = new javax.swing.JTable();
        panelOlahMk = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fieldkdMk = new javax.swing.JTextField();
        fieldnamaMk = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnsaveMk = new javax.swing.JLabel();
        btnCancelmk = new javax.swing.JLabel();
        btnhpsmk = new javax.swing.JLabel();
        btnviewMk = new javax.swing.JLabel();
        panelViewMK = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableviewMk = new javax.swing.JTable();
        panelOlahKelas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fieldkdKls = new javax.swing.JTextField();
        fieldKapKelas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btntmbhkelas = new javax.swing.JLabel();
        btnCancelkelas = new javax.swing.JLabel();
        btnHapuskls = new javax.swing.JLabel();
        btnviewkelas = new javax.swing.JLabel();
        panelViewKelas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableViewKelas = new javax.swing.JTable();
        panelOlahRuang = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        fieldkdRuang = new javax.swing.JTextField();
        fieldKapRuang = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnsaveruang = new javax.swing.JLabel();
        btncancelruang = new javax.swing.JLabel();
        btnHapusruang = new javax.swing.JLabel();
        btnviewRuang = new javax.swing.JLabel();
        panelViewRuang = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableViewRuang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        btnOlahData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-olah-data.png"))); // NOI18N
        btnOlahData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOlahDataMouseClicked(evt);
            }
        });

        btnOlahJadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-oahjadwal.png"))); // NOI18N

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-keluar.png"))); // NOI18N

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 245, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOlahJadwal)
                    .addComponent(btnExit)
                    .addComponent(btnOlahData))
                .addGap(278, 278, 278))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnOlahData)
                .addGap(18, 18, 18)
                .addComponent(btnOlahJadwal)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, "card9");

        btnDosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-dosen.png"))); // NOI18N

        btnMk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-matkul.png"))); // NOI18N

        btnKls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-kelas.png"))); // NOI18N

        btnRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-ruang.png"))); // NOI18N

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-back.png"))); // NOI18N

        javax.swing.GroupLayout panelmenuawalLayout = new javax.swing.GroupLayout(panelmenuawal);
        panelmenuawal.setLayout(panelmenuawalLayout);
        panelmenuawalLayout.setHorizontalGroup(
            panelmenuawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuawalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnDosen)
                .addGap(18, 18, 18)
                .addComponent(btnMk)
                .addGap(18, 18, 18)
                .addComponent(btnKls)
                .addGap(18, 18, 18)
                .addComponent(btnRuang)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        panelmenuawalLayout.setVerticalGroup(
            panelmenuawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmenuawalLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(panelmenuawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDosen)
                    .addComponent(btnMk)
                    .addComponent(btnKls)
                    .addComponent(btnRuang)
                    .addComponent(btnBack))
                .addGap(140, 140, 140))
        );

        getContentPane().add(panelmenuawal, "card2");

        btnInputjadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-input-jadwal.png"))); // NOI18N

        btnViewJadwalSemua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-semua.png"))); // NOI18N

        btnviewJadwal1bln.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-bulan.png"))); // NOI18N

        btnviewHari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-1hari.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-back.png"))); // NOI18N

        javax.swing.GroupLayout panelOlahjadwalLayout = new javax.swing.GroupLayout(panelOlahjadwal);
        panelOlahjadwal.setLayout(panelOlahjadwalLayout);
        panelOlahjadwalLayout.setHorizontalGroup(
            panelOlahjadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahjadwalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnInputjadwal)
                .addGap(18, 18, 18)
                .addComponent(btnViewJadwalSemua)
                .addGap(18, 18, 18)
                .addComponent(btnviewJadwal1bln)
                .addGap(18, 18, 18)
                .addComponent(btnviewHari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(128, 128, 128))
        );
        panelOlahjadwalLayout.setVerticalGroup(
            panelOlahjadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOlahjadwalLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(161, 161, 161))
            .addGroup(panelOlahjadwalLayout.createSequentialGroup()
                .addGroup(panelOlahjadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahjadwalLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(panelOlahjadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnviewJadwal1bln)
                            .addComponent(btnViewJadwalSemua)
                            .addComponent(btnInputjadwal)))
                    .addGroup(panelOlahjadwalLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnviewHari)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelOlahjadwal, "card3");

        javax.swing.GroupLayout panelInputJadwalLayout = new javax.swing.GroupLayout(panelInputJadwal);
        panelInputJadwal.setLayout(panelInputJadwalLayout);
        panelInputJadwalLayout.setHorizontalGroup(
            panelInputJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        panelInputJadwalLayout.setVerticalGroup(
            panelInputJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        getContentPane().add(panelInputJadwal, "card10");

        tableViewharijadwal.setBackground(new java.awt.Color(204, 204, 255));
        tableViewharijadwal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 204), new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        tableViewharijadwal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tableViewharijadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableViewharijadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableViewharijadwal.setGridColor(new java.awt.Color(0, 255, 102));
        tableViewharijadwal.setRequestFocusEnabled(false);
        tableViewharijadwal.setRowHeight(30);
        jScrollPane7.setViewportView(tableViewharijadwal);

        javax.swing.GroupLayout panelview1hariLayout = new javax.swing.GroupLayout(panelview1hari);
        panelview1hari.setLayout(panelview1hariLayout);
        panelview1hariLayout.setHorizontalGroup(
            panelview1hariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelview1hariLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelview1hariLayout.setVerticalGroup(
            panelview1hariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelview1hariLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        getContentPane().add(panelview1hari, "card8");

        tableviewjadwalbulan.setBackground(new java.awt.Color(204, 204, 255));
        tableviewjadwalbulan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 204), new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        tableviewjadwalbulan.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tableviewjadwalbulan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableviewjadwalbulan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableviewjadwalbulan.setGridColor(new java.awt.Color(0, 255, 102));
        tableviewjadwalbulan.setRequestFocusEnabled(false);
        tableviewjadwalbulan.setRowHeight(30);
        jScrollPane8.setViewportView(tableviewjadwalbulan);

        javax.swing.GroupLayout panelViewJadwalbulanLayout = new javax.swing.GroupLayout(panelViewJadwalbulan);
        panelViewJadwalbulan.setLayout(panelViewJadwalbulanLayout);
        panelViewJadwalbulanLayout.setHorizontalGroup(
            panelViewJadwalbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewJadwalbulanLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelViewJadwalbulanLayout.setVerticalGroup(
            panelViewJadwalbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewJadwalbulanLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        getContentPane().add(panelViewJadwalbulan, "card8");

        tableViewalljadwal.setBackground(new java.awt.Color(204, 204, 255));
        tableViewalljadwal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 204), new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        tableViewalljadwal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tableViewalljadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableViewalljadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableViewalljadwal.setGridColor(new java.awt.Color(0, 255, 102));
        tableViewalljadwal.setRequestFocusEnabled(false);
        tableViewalljadwal.setRowHeight(30);
        jScrollPane5.setViewportView(tableViewalljadwal);

        javax.swing.GroupLayout panelviewJadwalAllLayout = new javax.swing.GroupLayout(panelviewJadwalAll);
        panelviewJadwalAll.setLayout(panelviewJadwalAllLayout);
        panelviewJadwalAllLayout.setHorizontalGroup(
            panelviewJadwalAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewJadwalAllLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelviewJadwalAllLayout.setVerticalGroup(
            panelviewJadwalAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelviewJadwalAllLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        getContentPane().add(panelviewJadwalAll, "card8");

        panelOlahDosen.setPreferredSize(new java.awt.Dimension(483, 300));

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel4.setText("Kode Dosen  :");

        fieldkdosen.setBackground(new java.awt.Color(204, 204, 255));
        fieldkdosen.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fieldkdosen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldkdosen.setCaretColor(new java.awt.Color(153, 255, 153));

        fieldnamadosen.setBackground(new java.awt.Color(204, 204, 255));
        fieldnamadosen.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fieldnamadosen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldnamadosen.setCaretColor(new java.awt.Color(153, 255, 153));

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel5.setText("Nama Dosen :");

        btnsavedosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-tambahdata.png"))); // NOI18N

        btncanceldosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-cancel.png"))); // NOI18N

        btnhpsdosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-hapus.png"))); // NOI18N

        btnviewdosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-lihatdata.png"))); // NOI18N

        javax.swing.GroupLayout panelOlahDosenLayout = new javax.swing.GroupLayout(panelOlahDosen);
        panelOlahDosen.setLayout(panelOlahDosenLayout);
        panelOlahDosenLayout.setHorizontalGroup(
            panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahDosenLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahDosenLayout.createSequentialGroup()
                        .addComponent(btnviewdosen)
                        .addGap(18, 18, 18)
                        .addComponent(btncanceldosen))
                    .addGroup(panelOlahDosenLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelOlahDosenLayout.createSequentialGroup()
                                .addComponent(fieldnamadosen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnhpsdosen))
                            .addGroup(panelOlahDosenLayout.createSequentialGroup()
                                .addComponent(fieldkdosen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsavedosen)
                                .addGap(1, 1, 1)))))
                .addGap(46, 173, Short.MAX_VALUE))
        );
        panelOlahDosenLayout.setVerticalGroup(
            panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahDosenLayout.createSequentialGroup()
                .addGroup(panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahDosenLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fieldkdosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fieldnamadosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOlahDosenLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnsavedosen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhpsdosen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOlahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncanceldosen)
                    .addComponent(btnviewdosen))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(panelOlahDosen, "card4");

        tableViewDosen.setBackground(new java.awt.Color(204, 204, 255));
        tableViewDosen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 204), new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        tableViewDosen.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tableViewDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableViewDosen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableViewDosen.setGridColor(new java.awt.Color(0, 255, 102));
        tableViewDosen.setRequestFocusEnabled(false);
        tableViewDosen.setRowHeight(30);
        jScrollPane1.setViewportView(tableViewDosen);

        javax.swing.GroupLayout panelViewDosenLayout = new javax.swing.GroupLayout(panelViewDosen);
        panelViewDosen.setLayout(panelViewDosenLayout);
        panelViewDosenLayout.setHorizontalGroup(
            panelViewDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDosenLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelViewDosenLayout.setVerticalGroup(
            panelViewDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDosenLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        getContentPane().add(panelViewDosen, "card8");

        panelOlahMk.setPreferredSize(new java.awt.Dimension(483, 300));

        jLabel12.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel12.setText("Kode MK  :");

        fieldkdMk.setBackground(new java.awt.Color(204, 204, 255));
        fieldkdMk.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fieldkdMk.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldkdMk.setCaretColor(new java.awt.Color(153, 255, 153));

        fieldnamaMk.setBackground(new java.awt.Color(204, 204, 255));
        fieldnamaMk.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fieldnamaMk.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldnamaMk.setCaretColor(new java.awt.Color(153, 255, 153));

        jLabel13.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel13.setText("Nama MK :");

        btnsaveMk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-tambahdata.png"))); // NOI18N

        btnCancelmk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-cancel.png"))); // NOI18N

        btnhpsmk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-hapus.png"))); // NOI18N

        btnviewMk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-lihatdata.png"))); // NOI18N

        javax.swing.GroupLayout panelOlahMkLayout = new javax.swing.GroupLayout(panelOlahMk);
        panelOlahMk.setLayout(panelOlahMkLayout);
        panelOlahMkLayout.setHorizontalGroup(
            panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahMkLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahMkLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(29, 29, 29)
                        .addGroup(panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldkdMk, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(fieldnamaMk))
                        .addGap(30, 30, 30)
                        .addGroup(panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsaveMk)
                            .addComponent(btnhpsmk)))
                    .addGroup(panelOlahMkLayout.createSequentialGroup()
                        .addComponent(btnviewMk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelmk)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        panelOlahMkLayout.setVerticalGroup(
            panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahMkLayout.createSequentialGroup()
                .addGroup(panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahMkLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(fieldkdMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(fieldnamaMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOlahMkLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnsaveMk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhpsmk)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOlahMkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelmk)
                    .addComponent(btnviewMk))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(panelOlahMk, "card4");

        tableviewMk.setBackground(new java.awt.Color(204, 204, 255));
        tableviewMk.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 204), new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        tableviewMk.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tableviewMk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableviewMk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableviewMk.setGridColor(new java.awt.Color(0, 255, 102));
        tableviewMk.setRequestFocusEnabled(false);
        tableviewMk.setRowHeight(30);
        jScrollPane2.setViewportView(tableviewMk);

        javax.swing.GroupLayout panelViewMKLayout = new javax.swing.GroupLayout(panelViewMK);
        panelViewMK.setLayout(panelViewMKLayout);
        panelViewMKLayout.setHorizontalGroup(
            panelViewMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewMKLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelViewMKLayout.setVerticalGroup(
            panelViewMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewMKLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        getContentPane().add(panelViewMK, "card8");

        panelOlahKelas.setPreferredSize(new java.awt.Dimension(483, 300));

        jLabel8.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel8.setText("Kode Kelas :");

        fieldkdKls.setBackground(new java.awt.Color(204, 204, 255));
        fieldkdKls.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fieldkdKls.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldkdKls.setCaretColor(new java.awt.Color(153, 255, 153));

        fieldKapKelas.setBackground(new java.awt.Color(204, 204, 255));
        fieldKapKelas.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fieldKapKelas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldKapKelas.setCaretColor(new java.awt.Color(153, 255, 153));

        jLabel9.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel9.setText("Kapasitas   :");

        btntmbhkelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-tambahdata.png"))); // NOI18N

        btnCancelkelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-cancel.png"))); // NOI18N

        btnHapuskls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-hapus.png"))); // NOI18N

        btnviewkelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-lihatdata.png"))); // NOI18N

        javax.swing.GroupLayout panelOlahKelasLayout = new javax.swing.GroupLayout(panelOlahKelas);
        panelOlahKelas.setLayout(panelOlahKelasLayout);
        panelOlahKelasLayout.setHorizontalGroup(
            panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahKelasLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahKelasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldkdKls, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldKapKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapuskls)
                            .addComponent(btntmbhkelas)))
                    .addGroup(panelOlahKelasLayout.createSequentialGroup()
                        .addComponent(btnviewkelas)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelkelas)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        panelOlahKelasLayout.setVerticalGroup(
            panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahKelasLayout.createSequentialGroup()
                .addGroup(panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahKelasLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(fieldkdKls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(fieldKapKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOlahKelasLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btntmbhkelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapuskls)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelkelas)
                    .addComponent(btnviewkelas))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(panelOlahKelas, "card4");

        tableViewKelas.setBackground(new java.awt.Color(204, 204, 255));
        tableViewKelas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 204), new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        tableViewKelas.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tableViewKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableViewKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableViewKelas.setGridColor(new java.awt.Color(0, 255, 102));
        tableViewKelas.setRequestFocusEnabled(false);
        tableViewKelas.setRowHeight(30);
        jScrollPane3.setViewportView(tableViewKelas);

        javax.swing.GroupLayout panelViewKelasLayout = new javax.swing.GroupLayout(panelViewKelas);
        panelViewKelas.setLayout(panelViewKelasLayout);
        panelViewKelasLayout.setHorizontalGroup(
            panelViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewKelasLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelViewKelasLayout.setVerticalGroup(
            panelViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewKelasLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        getContentPane().add(panelViewKelas, "card8");

        panelOlahRuang.setPreferredSize(new java.awt.Dimension(483, 300));

        jLabel16.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel16.setText("Kode Ruang :");

        fieldkdRuang.setBackground(new java.awt.Color(204, 204, 255));
        fieldkdRuang.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fieldkdRuang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldkdRuang.setCaretColor(new java.awt.Color(153, 255, 153));

        fieldKapRuang.setBackground(new java.awt.Color(204, 204, 255));
        fieldKapRuang.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fieldKapRuang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldKapRuang.setCaretColor(new java.awt.Color(153, 255, 153));

        jLabel17.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel17.setText("Kapasitas     :");

        btnsaveruang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-tambahdata.png"))); // NOI18N

        btncancelruang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-cancel.png"))); // NOI18N

        btnHapusruang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-hapus.png"))); // NOI18N

        btnviewRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/gambar/btn-lihatdata.png"))); // NOI18N

        javax.swing.GroupLayout panelOlahRuangLayout = new javax.swing.GroupLayout(panelOlahRuang);
        panelOlahRuang.setLayout(panelOlahRuangLayout);
        panelOlahRuangLayout.setHorizontalGroup(
            panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahRuangLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahRuangLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(29, 29, 29)
                        .addGroup(panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldkdRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldKapRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapusruang)
                            .addComponent(btnsaveruang)))
                    .addGroup(panelOlahRuangLayout.createSequentialGroup()
                        .addComponent(btnviewRuang)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelruang)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        panelOlahRuangLayout.setVerticalGroup(
            panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlahRuangLayout.createSequentialGroup()
                .addGroup(panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlahRuangLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(fieldkdRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(fieldKapRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOlahRuangLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnsaveruang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusruang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOlahRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncancelruang)
                    .addComponent(btnviewRuang))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(panelOlahRuang, "card4");

        tableViewRuang.setBackground(new java.awt.Color(204, 204, 255));
        tableViewRuang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 204), new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        tableViewRuang.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tableViewRuang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableViewRuang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableViewRuang.setGridColor(new java.awt.Color(0, 255, 102));
        tableViewRuang.setRequestFocusEnabled(false);
        tableViewRuang.setRowHeight(30);
        jScrollPane4.setViewportView(tableViewRuang);

        javax.swing.GroupLayout panelViewRuangLayout = new javax.swing.GroupLayout(panelViewRuang);
        panelViewRuang.setLayout(panelViewRuangLayout);
        panelViewRuangLayout.setHorizontalGroup(
            panelViewRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewRuangLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelViewRuangLayout.setVerticalGroup(
            panelViewRuangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewRuangLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        getContentPane().add(panelViewRuang, "card8");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOlahDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOlahDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOlahDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guimenu().setVisible(true);

            }
        });
    }
     public void addMouseListeners(MouseListener me) {
        btnOlahData.addMouseListener(me);
        btnOlahJadwal.addMouseListener(me);
        btnExit.addMouseListener(me);
        btnDosen.addMouseListener(me);
        btnMk.addMouseListener(me);
        btnKls.addMouseListener(me);
        btnRuang.addMouseListener(me);
    }

    public Graphics getG() {
        return g;
    }

    public JLabel getBtnBack() {
        return btnBack;
    }

    public JLabel getBtnCancelkelas() {
        return btnCancelkelas;
    }

    public JLabel getBtnCancelmk() {
        return btnCancelmk;
    }

    public JLabel getBtnDosen() {
        return btnDosen;
    }

    public JLabel getBtnHapuskls() {
        return btnHapuskls;
    }

    public JLabel getBtnHapusruang() {
        return btnHapusruang;
    }

    public JLabel getBtnInputjadwal() {
        return btnInputjadwal;
    }

    public JLabel getBtnKls() {
        return btnKls;
    }

    public JLabel getBtnMk() {
        return btnMk;
    }

    public Image getImg() {
        return img;
    }

    public Image getDimg() {
        return dimg;
    }

    public ImageIcon getImageIcon() {
        return imageIcon;
    }

    public JLabel getBtnRuang() {
        return btnRuang;
    }

    public JLabel getBtnViewJadwalSemua() {
        return btnViewJadwalSemua;
    }

    public JLabel getBtncanceldosen() {
        return btncanceldosen;
    }

    public JLabel getBtncancelruang() {
        return btncancelruang;
    }

    public JLabel getBtnhpsdosen() {
        return btnhpsdosen;
    }

    public JLabel getBtnhpsmk() {
        return btnhpsmk;
    }

    public JLabel getBtnsaveMk() {
        return btnsaveMk;
    }

    public JLabel getBtnsavedosen() {
        return btnsavedosen;
    }

    public JLabel getBtnsaveruang() {
        return btnsaveruang;
    }

    public JLabel getBtntmbhkelas() {
        return btntmbhkelas;
    }

    public JLabel getBtnviewHari() {
        return btnviewHari;
    }

    public JLabel getBtnviewJadwal1bln() {
        return btnviewJadwal1bln;
    }

    public JLabel getBtnviewMk() {
        return btnviewMk;
    }

    public JLabel getBtnviewRuang() {
        return btnviewRuang;
    }

    public JLabel getBtnviewdosen() {
        return btnviewdosen;
    }

    public JLabel getBtnviewkelas() {
        return btnviewkelas;
    }

    public JOptionPane getJpane() {
        return jpane;
    }

    public JTextField getFieldKapKelas() {
        return fieldKapKelas;
    }

    public JTextField getFieldKapRuang() {
        return fieldKapRuang;
    }

    public JTextField getFieldkdKls() {
        return fieldkdKls;
    }

    public JTextField getFieldkdMk() {
        return fieldkdMk;
    }

    public JTextField getFieldkdRuang() {
        return fieldkdRuang;
    }

    public JTextField getFieldkdosen() {
        return fieldkdosen;
    }

    public JTextField getFieldnamaMk() {
        return fieldnamaMk;
    }

    public JTextField getFieldnamadosen() {
        return fieldnamadosen;
    }

 

    public JLabel getjLabel10() {
        return btnOlahJadwal;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }


    public JLabel getjLabel3() {
        return btnOlahData;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel7() {
        return btnExit;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getjTable1() {
        return tableViewDosen;
    }

    public JPanel getPanelInputJadwal() {
        return panelInputJadwal;
    }

    public JPanel getPanelMenu() {
        return panelMenu;
    }

    public JPanel getPanelOlahDosen() {
        return panelOlahDosen;
    }

    public JPanel getPanelOlahKelas() {
        return panelOlahKelas;
    }

    public JPanel getPanelOlahMk() {
        return panelOlahMk;
    }

    public JPanel getPanelOlahRuang() {
        return panelOlahRuang;
    }

    public JPanel getPanelOlahjadwal() {
        return panelOlahjadwal;
    }

    public JLabel getBtnExit() {
        return btnExit;
    }

    public JLabel getBtnOlahData() {
        return btnOlahData;
    }

    public JLabel getBtnOlahJadwal() {
        return btnOlahJadwal;
    }

    public JPanel getPanelViewDosen() {
        return panelViewDosen;
    }

    public JPanel getPanelmenuawal() {
        return panelmenuawal;
    }


    public JPanel getPanelViewJadwalbulan() {
        return panelViewJadwalbulan;
    }

    public JPanel getPanelViewKelas() {
        return panelViewKelas;
    }

    public JPanel getPanelViewMK() {
        return panelViewMK;
    }

    public JPanel getPanelViewRuang() {
        return panelViewRuang;
    }

    public JPanel getPanelview1hari() {
        return panelview1hari;
    }

    public JPanel getPanelviewJadwalAll() {
        return panelviewJadwalAll;
    }

    public JTable getTableViewDosen() {
        return tableViewDosen;
    }

    public JTable getTableViewKelas() {
        return tableViewKelas;
    }

    public JTable getTableViewRuang() {
        return tableViewRuang;
    }

    public JTable getTableViewalljadwal() {
        return tableViewalljadwal;
    }

    public JTable getTableViewharijadwal() {
        return tableViewharijadwal;
    }

    public JTable getTableviewMk() {
        return tableviewMk;
    }

    public JTable getTableviewjadwalbulan() {
        return tableviewjadwalbulan;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCancelkelas;
    private javax.swing.JLabel btnCancelmk;
    private javax.swing.JLabel btnDosen;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHapuskls;
    private javax.swing.JLabel btnHapusruang;
    private javax.swing.JLabel btnInputjadwal;
    private javax.swing.JLabel btnKls;
    private javax.swing.JLabel btnMk;
    Image img = null;
    Image dimg=null;
    ImageIcon imageIcon=null;
    private javax.swing.JLabel btnOlahData;
    private javax.swing.JLabel btnOlahJadwal;
    private javax.swing.JLabel btnRuang;
    private javax.swing.JLabel btnViewJadwalSemua;
    private javax.swing.JLabel btncanceldosen;
    private javax.swing.JLabel btncancelruang;
    private javax.swing.JLabel btnhpsdosen;
    private javax.swing.JLabel btnhpsmk;
    private javax.swing.JLabel btnsaveMk;
    private javax.swing.JLabel btnsavedosen;
    private javax.swing.JLabel btnsaveruang;
    private javax.swing.JLabel btntmbhkelas;
    private javax.swing.JLabel btnviewHari;
    private javax.swing.JLabel btnviewJadwal1bln;
    private javax.swing.JLabel btnviewMk;
    private javax.swing.JLabel btnviewRuang;
    private javax.swing.JLabel btnviewdosen;
    private javax.swing.JLabel btnviewkelas;
    private javax.swing.JTextField fieldKapKelas;
    private javax.swing.JTextField fieldKapRuang;
    private javax.swing.JTextField fieldkdKls;
    private javax.swing.JTextField fieldkdMk;
    private javax.swing.JTextField fieldkdRuang;
    private javax.swing.JTextField fieldkdosen;
    private javax.swing.JTextField fieldnamaMk;
    private javax.swing.JTextField fieldnamadosen;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JOptionPane jpane;
    private javax.swing.JPanel panelInputJadwal;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelOlahDosen;
    private javax.swing.JPanel panelOlahKelas;
    private javax.swing.JPanel panelOlahMk;
    private javax.swing.JPanel panelOlahRuang;
    private javax.swing.JPanel panelOlahjadwal;
    private javax.swing.JPanel panelViewDosen;
    private javax.swing.JPanel panelViewJadwalbulan;
    private javax.swing.JPanel panelViewKelas;
    private javax.swing.JPanel panelViewMK;
    private javax.swing.JPanel panelViewRuang;
    private javax.swing.JPanel panelmenuawal;
    private javax.swing.JPanel panelview1hari;
    private javax.swing.JPanel panelviewJadwalAll;
    private javax.swing.JTable tableViewDosen;
    private javax.swing.JTable tableViewKelas;
    private javax.swing.JTable tableViewRuang;
    private javax.swing.JTable tableViewalljadwal;
    private javax.swing.JTable tableViewharijadwal;
    private javax.swing.JTable tableviewMk;
    private javax.swing.JTable tableviewjadwalbulan;
    // End of variables declaration//GEN-END:variables

}
